---
- name: set root password
  user:
    name=root
    password="{{ root_password }}"

- name: install additional packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    # - vim
    # - git-core
    # - httpie
    - unzip
    - python-setuptools

- name: install pip
  easy_install:
    name=pip
    state=present