---
- name: set root password
  user:
    name=root
    password="{{ root_password }}"

- name: install additional packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - vim
    - git-core

- name: install unzip
  apt:
    pkg=unzip
    state=present

- name: install python-setuptools
  apt:
    pkg=python-setuptools
    state=present

- name: install pip
  easy_install:
    name=pip
    state=present