---
- name: download and install consul
  unarchive:
    src=https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip
    dest=/usr/local/bin
    copy=no

- name: create consul group
  group: >
    name={{consul_group}}
    state=present

- name: create consul user
  user: >
    name={{consul_user}}
    group={{consul_group}}    

- name: create consul directory
  file: >
    state=directory
    path={{ item }}
    owner={{consul_user}}
    group={{consul_group}}
  with_items:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: set ownership
  file: >
    state=directory
    path={{consul_home}}
    owner={{consul_user}}
    group={{consul_group}}
    recurse=yes    

- name: copy consul systemd script
  template: >
    src=consul.systemd.j2
    dest=/etc/systemd/system/consul.service
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755
  notify:
    - reload systemd
    - restart consul

- name: consul config file
  template: >
    src=consul.json.j2
    dest={{ consul_config_file }}
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755    
