---
- name: deploy simple app application
  docker:
    name: simple_app
    image: jsayar/simple_app
    state: reloaded
    pull: always
    ports:
      - "127.0.0.1:8080:9292"

- name: register service in consul
  consul:
    service_name: simple_app
    service_port: 80