---
- hosts: all
  roles:
    - base

- hosts: consul
  roles:
    - nginx
    - consul

# - hosts: router
#   roles:
#     - nginx
#     - consul

- hosts: webapp
  roles:
    - nginx
    - consul  
    - docker
    - app
